"""scripts/ — ArgoCD skill 内置工具集（namespace package）。

本目录本身不是一个普通 Python 包，而是一个 PEP 420 namespace package。
其子包（argocd_cli_gen、argocd_api、argocd_insight、argocd_deploy_stats）
各自有独立的 __init__.py，可通过以下方式调用：

    python -m scripts.argocd_cli_gen ...
    python -m scripts.argocd_api ...
    python -m scripts.argocd_insight ...
    python -m scripts.argocd_deploy_stats.stats ...

同时也支持从 repo root 直接调用（文档写法）：
    python -m argocd_cli_gen ...
    python -m argocd_api ...
    python -m argocd_insight ...
    python -m argocd_deploy_stats.stats ...

后者通过 repo root 的 __init__.py（将本目录加入 sys.path）和各工具的
独立入口文件（argocd_api.py 等）实现。
"""
