"""多源/不支持字段 YAML 回退收集。

设计：收集 Tier.MULTI_SOURCE（注意：不含 MULTI_SOURCE_HELM，后者由 renderer 走
``argocd app create -f``）与 mapper 报告的 patches/components 等不支持字段的原始
YAML 整体，输出到单一 multi-document YAML 文件，由调用方用 kubectl apply -f 兜底。
"""

from __future__ import annotations

import datetime as _dt
from dataclasses import dataclass, field
from pathlib import Path

import yaml

from .mapper import UnsupportedField
from .parser import LoadedManifest, Tier


FALLBACK_HEADER = """# Generated by argocd-cli-gen at {timestamp}
# 这些 Application YAML 含 argocd CLI 不支持的字段（多源 spec.sources / kustomize.patches 等），
# 请使用 kubectl 直接应用：
#     kubectl -n argocd apply -f 99_multisource_fallback.yaml
#
# 每条 Application 之前的注释行标注了原始路径与回退原因。
"""


@dataclass
class FallbackEntry:
    path: Path
    name: str
    reason: str       # multi_source / unsupported_kustomize_field / ...
    fields: list[str] = field(default_factory=list)   # 涉及的字段（可选）


@dataclass
class FallbackBundle:
    entries: list[FallbackEntry] = field(default_factory=list)
    yaml_body: str = ""


def reasons_for(lm: LoadedManifest) -> list[str]:
    """判定一个 LoadedManifest 是否需要 kubectl-apply YAML 回退；返回原因列表（空 = 不需要）。

    这是 renderer / fallback 共用的省判定源——renderer 用它跳过这些项不进主脚本，
    fallback 用它把它们整体收集到 99_multisource_fallback.yaml。

    注意 ``Tier.MULTI_SOURCE_HELM``（Helm chart + values ref 模式）不在此列：
    这类应用由 ``renderer`` 通过 ``argocd app create -f <yaml>`` 直接处理，
    不再走 ``kubectl apply`` 通道。
    """
    reasons: list[str] = []
    if lm.tier == Tier.MULTI_SOURCE:
        reasons.append("multi_source")

    kus = (((lm.manifest.get("spec") or {}).get("source") or {}).get("kustomize") or {})
    if kus.get("patches"):
        reasons.append("kustomize.patches")
    if kus.get("components"):
        reasons.append("kustomize.components")

    return reasons


def collect(loaded: list[LoadedManifest], timestamp: str | None = None) -> FallbackBundle:
    """从 loaded 列表中挑出需要 YAML 回退的项。

    判定规则统一使用 ``reasons_for``：
      1. tier == MULTI_SOURCE → 整文件回退
      2. spec.source.kustomize.patches/components 字段存在 → 整文件回退

    timestamp 由调用方传入以保持同 run 内多产物的时间戳一致；缺省时自取一次。
    """
    bundle = FallbackBundle()
    docs: list[dict] = []

    for lm in loaded:
        reasons = reasons_for(lm)
        if not reasons:
            continue

        bundle.entries.append(FallbackEntry(
            path=lm.path,
            name=lm.name,
            reason=reasons[0],
            fields=reasons,
        ))
        docs.append(lm.manifest)

    if not docs:
        return bundle

    ts = timestamp or _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    parts = [FALLBACK_HEADER.format(timestamp=ts)]
    for entry, doc in zip(bundle.entries, docs):
        parts.append(f"# source: {entry.path}\n# reason: {entry.reason}\n")
        parts.append(yaml.safe_dump(doc, sort_keys=False, allow_unicode=True))
        parts.append("---\n")

    bundle.yaml_body = "".join(parts).rstrip("-\n") + "\n"
    return bundle


def write_fallback(bundle: FallbackBundle, output_dir: Path) -> Path | None:
    """落盘回退 YAML。无内容时返回 None。"""
    if not bundle.entries:
        return None
    output_dir.mkdir(parents=True, exist_ok=True)
    out_path = output_dir / "99_multisource_fallback.yaml"
    out_path.write_text(bundle.yaml_body, encoding="utf-8")
    return out_path
