"""Shell 脚本渲染器。

按层级分桶 → 每桶一个 shell 脚本 → 每个脚本配套 dry-run 副本。

认证模型：
    00_preflight.sh 通过 `argocd login` 建立全局 session
    （写入 ~/.config/argocd/config 的当前 context），凭证通过环境变量传递
    （不作为 CLI 参数，避免 ps aux 可见），后续脚本中的
    `argocd app create` 命令不再重复传 --server / --auth-token / --grpc-web。
"""

from __future__ import annotations

import datetime as _dt
from dataclasses import dataclass, field
from pathlib import Path

import yaml

from . import fallback
from .mapper import MappedApp, map_single_source, safe_app_name
from .parser import LoadedManifest, Tier


SCRIPT_HEADER = """#!/usr/bin/env bash
# Generated by argocd-cli-gen at {timestamp}
# Tier: {tier}    Apps: {count}    Source dir: {source_dir}
#
# 前置条件：
#   1) 已执行 `bash 00_preflight.sh`（完成 argocd login）
#   2) 或手动 `export ARGOCD_AUTH_TOKEN && argocd login $ARGOCD_SERVER --grpc-web`
#
set -euo pipefail
IFS=$'\\n\\t'

"""

PREFLIGHT_SCRIPT = """#!/usr/bin/env bash
# Generated by argocd-cli-gen at {timestamp}
# Pre-flight: 校验 argocd CLI、env、并完成一次性登录
set -euo pipefail
IFS=$'\\n\\t'

# ── 0. trim 所有 ARGOCD_* 环境变量（去除首尾空白） ───────────────────
for var in ARGOCD_SERVER ARGOCD_AUTH_TOKEN ARGOCD_USERNAME ARGOCD_PASSWORD; do
  if [[ -v "$var" ]]; then
    # 循环去除尾部换行/空格，再去首部（防止多行 token 的尾部换行问题）
    while [[ "${{!var}}" =~ [[:space:]]$ ]]; do
      declare "$var=${{!var%[[:space:]]}}"
    done
    while [[ "${{!var}}" =~ ^[[:space:]] ]]; do
      declare "$var=${{!var#[[:space:]]}}"
    done
  fi
done

# ── 1. ARGOCD_SERVER 必填 + URL 格式校验 ─────────────────────────────
: "${{ARGOCD_SERVER:?未设置 ARGOCD_SERVER 环境变量，参见 .env.example}}"

if [[ ! "$ARGOCD_SERVER" =~ ^https?:// ]]; then
  echo "[error] ARGOCD_SERVER 格式错误：$ARGOCD_SERVER" >&2
  echo "       正确格式示例：https://argocd.hd123.com/dnet-int" >&2
  echo "       必须以 http:// 或 https:// 开头" >&2
  exit 1
fi

# ── 2. argocd CLI 可执行性检查 ───────────────────────────────────────
if ! command -v argocd >/dev/null 2>&1; then
  echo "[error] argocd CLI not found in PATH" >&2
  echo "       参见 references/cli-installation.md 安装 ArgoCD CLI" >&2
  exit 2
fi

argocd version --client

# ── 3. 认证凭证检测（优先级：token > 用户名密码） ─────────────────────
if [[ -n "${{ARGOCD_AUTH_TOKEN:-}}" ]]; then
  echo "[preflight] 使用 ARGOCD_AUTH_TOKEN 登录 → $ARGOCD_SERVER"
  # ponetail: credentials NOT passed as CLI args — let argocd read env vars directly.
  # This avoids credential exposure in ps aux / process argv.
  export ARGOCD_AUTH_TOKEN
  argocd login "$ARGOCD_SERVER" --grpc-web
elif [[ -n "${{ARGOCD_USERNAME:-}}" && -n "${{ARGOCD_PASSWORD:-}}" ]]; then
  echo "[preflight] 使用 ARGOCD_USERNAME/PASSWORD 登录 → $ARGOCD_SERVER"
  export ARGOCD_USERNAME ARGOCD_PASSWORD
  argocd login "$ARGOCD_SERVER" --grpc-web
else
  echo "[error] 缺少认证凭证：需要配置以下任一方式：" >&2
  echo "       方式一：ARGOCD_AUTH_TOKEN（推荐）" >&2
  echo "       方式二：ARGOCD_USERNAME + ARGOCD_PASSWORD" >&2
  echo "       参见 .env.example" >&2
  exit 1
fi

# ── 4. 登录后会话校验 ────────────────────────────────────────────────
argocd account get-user-info

echo "[ok] pre-flight checks passed; session ready"
"""

RUN_ALL_SCRIPT = """#!/usr/bin/env bash
# Generated by argocd-cli-gen at {timestamp}
# 串行执行所有生成的脚本（按依赖顺序）
set -euo pipefail
IFS=$'\\n\\t'
cd "$(dirname "$0")"

bash 00_preflight.sh
{infra_line}
{root_line}
{workload_line}
{helm_line}

echo "[done] all argocd apps applied"
"""

RUN_ALL_DRY_SCRIPT = """#!/usr/bin/env bash
# Generated by argocd-cli-gen at {timestamp}
# Dry-run 串行模拟：调用各 tier 的 *.dry-run.sh
# 每个命令追加 --validate=false，跳过 ArgoCD 服务端 manifest 校验
#（仍需 preflight 登录，但不会真正创建 Application）。
# Fallback YAML 如需校验，请手动：
#   kubectl -n argocd apply -f 99_multisource_fallback.yaml --dry-run=client
set -euo pipefail
IFS=$'\\n\\t'
cd "$(dirname "$0")"

bash 00_preflight.sh
{infra_line}
{root_line}
{workload_line}
{helm_line}

echo "[done] all argocd apps dry-run simulated (no changes applied)"
"""


HELM_SCRIPT_HEADER = """#!/usr/bin/env bash
# Generated by argocd-cli-gen at {timestamp}
# Tier: {tier}    Apps: {count}    Source dir: {source_dir}
#
# 多源 Helm + $values 模式：argocd CLI 不支持用 flag 描述多源，
# 这里改为对每个应用执行 `argocd app create -f helm-apps/<name>.yaml --upsert`，
# 由 argocd 服务端解析整段多源 spec。
#
# 前置条件：
#   1) 已执行 `bash 00_preflight.sh`（完成 argocd login）
#   2) helm-apps/ 子目录中的 YAML 与本脚本一同生成，保持相对路径关系
#
set -euo pipefail
IFS=$'\\n\\t'
cd "$(dirname "$0")"

"""


# 各层级输出文件名
TIER_FILES: dict[Tier, str] = {
    Tier.INFRA_ROOT: "05_infra_roots.sh",
    Tier.ROOT_APP: "10_app_roots.sh",
    Tier.OPS_APP: "20_workloads_ops.sh",
    Tier.BUSINESS_APP: "30_workloads_business.sh",
    Tier.MULTI_SOURCE_HELM: "40_workloads_helm.sh",
}

# 多源 Helm 应用的独立 YAML 落盘目录（相对 output 目录）
HELM_APPS_DIR = "helm-apps"

# 多源回退文件
MULTISOURCE_FALLBACK_FILE = "99_multisource_fallback.yaml"


@dataclass
class RenderedScript:
    relative_path: str             # 相对 output 目录的文件名
    body: str                      # 文件内容
    dry_run_body: str | None = None  # dry-run 副本内容，None 表示无需生成


@dataclass
class ExtraFile:
    """非脚本类的附属产物（如 helm-apps/<name>.yaml）。"""

    relative_path: str
    body: str
    executable: bool = False


@dataclass
class RenderOptions:
    upsert: bool = True
    emit_dry_run: bool = True
    sleep_seconds: float = 0.0


def _render_one_app(lm: LoadedManifest, opts: RenderOptions) -> tuple[str, MappedApp]:
    """渲染单个 Application 的 CLI 命令块。"""
    mapped = map_single_source(lm.manifest)
    header = f"# --- {lm.path} (tier={lm.tier.value}, name={lm.name}) ---"
    body = mapped.render(upsert=opts.upsert)
    block = f"{header}\n{body}\n"
    if opts.sleep_seconds > 0:
        block += f"sleep {opts.sleep_seconds}\n"
    block += "\n"
    return block, mapped


def _now_utc_iso() -> str:
    return _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _render_tier(
    tier: Tier,
    items: list[LoadedManifest],
    source_dir: Path,
    opts: RenderOptions,
    timestamp: str,
) -> tuple[RenderedScript, list[MappedApp]]:
    """渲染一个层级的所有 Application 到一个 shell 脚本。"""
    header = SCRIPT_HEADER.format(
        timestamp=timestamp,
        tier=tier.value,
        count=len(items),
        source_dir=source_dir,
    )

    mapped_apps: list[MappedApp] = []
    body_chunks: list[str] = []
    dry_chunks: list[str] = []

    for lm in items:
        block, mapped = _render_one_app(lm, opts)
        mapped_apps.append(mapped)
        body_chunks.append(block)
        dry_chunks.append(_to_dry_run_block(block))

    body = header + "".join(body_chunks)
    body += 'echo "[ok] tier {tier} applied {count} apps"\n'.format(
        tier=tier.value, count=len(items)
    )

    dry_body: str | None = None
    if opts.emit_dry_run:
        dry_header = header.replace(
            "Tier: ", "Tier (dry-run): "
        )
        dry_body = dry_header + "".join(dry_chunks)
        dry_body += 'echo "[ok] dry-run tier {tier} simulated {count} apps"\n'.format(
            tier=tier.value, count=len(items)
        )

    return (
        RenderedScript(
            relative_path=TIER_FILES[tier],
            body=body,
            dry_run_body=dry_body,
        ),
        mapped_apps,
    )


def _to_dry_run_block(block: str) -> str:
    """把一个 'argocd app create ...' 块转换为 dry-run 版本（跳过服务端校验）。

    注意：argocd CLI 没有 --dry-run/-o yaml 组合；改用 --validate=false
    跳过 ArgoCD 服务端的 manifest 校验，但仍需认证（preflight 仍需真实 login）。
    """
    if "argocd app create " not in block:
        return block
    return block.replace(
        "argocd app create ",
        "argocd app create --validate=false ",
    )


def _render_helm_multisource_tier(
    items: list[LoadedManifest],
    source_dir: Path,
    opts: RenderOptions,
    timestamp: str,
) -> tuple[RenderedScript, list[ExtraFile]]:
    """渲染 MULTI_SOURCE_HELM 层级。

    与其他 tier 不同：每个应用对应一份 ``helm-apps/<name>.yaml`` 文件 + 一条
    ``argocd app create -f helm-apps/<name>.yaml --upsert`` 命令。
    YAML 即原 manifest 整体导出（保持多源 spec 不变），由 argocd 服务端解析。
    """
    header = HELM_SCRIPT_HEADER.format(
        timestamp=timestamp,
        tier=Tier.MULTI_SOURCE_HELM.value,
        count=len(items),
        source_dir=source_dir,
    )

    body_chunks: list[str] = []
    dry_chunks: list[str] = []
    extras: list[ExtraFile] = []

    for lm in items:
        app_name = safe_app_name(lm.name) or lm.path.stem
        yaml_relpath = f"{HELM_APPS_DIR}/{app_name}.yaml"
        yaml_body = _dump_application_yaml(lm.manifest, lm.path)
        extras.append(ExtraFile(relative_path=yaml_relpath, body=yaml_body))

        cmd_header = (
            f"# --- {lm.path} (tier={lm.tier.value}, name={lm.name}) ---"
        )
        cmd = _render_helm_create_command(app_name, yaml_relpath, opts)
        block = f"{cmd_header}\n{cmd}\n"
        if opts.sleep_seconds > 0:
            block += f"sleep {opts.sleep_seconds}\n"
        block += "\n"
        body_chunks.append(block)

        dry_cmd = _render_helm_create_command(
            app_name, yaml_relpath, opts, dry_run=True,
        )
        dry_block = f"{cmd_header}\n{dry_cmd}\n\n"
        dry_chunks.append(dry_block)

    body = header + "".join(body_chunks)
    body += 'echo "[ok] tier {tier} applied {count} apps"\n'.format(
        tier=Tier.MULTI_SOURCE_HELM.value, count=len(items),
    )

    dry_body: str | None = None
    if opts.emit_dry_run:
        dry_header = header.replace("Tier: ", "Tier (dry-run): ")
        dry_body = dry_header + "".join(dry_chunks)
        dry_body += 'echo "[ok] dry-run tier {tier} simulated {count} apps"\n'.format(
            tier=Tier.MULTI_SOURCE_HELM.value, count=len(items),
        )

    return (
        RenderedScript(
            relative_path=TIER_FILES[Tier.MULTI_SOURCE_HELM],
            body=body,
            dry_run_body=dry_body,
        ),
        extras,
    )


def _render_helm_create_command(
    app_name: str,
    yaml_relpath: str,
    opts: RenderOptions,
    *,
    dry_run: bool = False,
) -> str:
    """渲染单条 ``argocd app create -f ...`` 命令。

    位置参数 ``app_name`` 与 ``--file`` 同时给出：argocd CLI 允许，且能保证 YAML
    内 ``metadata.name`` 与 CLI 命名一致（防止下划线未替换的差异）。
    """
    lines = ["argocd app create"]
    if dry_run:
        lines.append("--dry-run -o yaml")
    lines.extend([app_name, f"-f {yaml_relpath}"])
    if opts.upsert:
        lines.append("--upsert")
    return " \\\n  ".join(lines)


def _dump_application_yaml(manifest: dict, source_path: Path) -> str:
    """把单个 Application manifest 导出为带溯源注释的 YAML 字符串。"""
    header = (
        f"# Generated by argocd-cli-gen\n"
        f"# source: {source_path}\n"
        f"# 由 `argocd app create -f` 直接应用，保留多源 spec.sources 原样。\n"
    )
    body = yaml.safe_dump(manifest, sort_keys=False, allow_unicode=True)
    return header + body


def render_preflight(timestamp: str | None = None) -> RenderedScript:
    ts = timestamp or _now_utc_iso()
    return RenderedScript(
        relative_path="00_preflight.sh",
        body=PREFLIGHT_SCRIPT.format(timestamp=ts),
        dry_run_body=None,
    )


def _dry_filename(name: str) -> str:
    """将 tier 脚本名替换为对应 dry-run 副本名（保留前缀编号与后缀）。"""
    return name.replace(".sh", ".dry-run.sh")


def render_run_all(
    included_tiers: set[Tier],
    timestamp: str | None = None,
    *,
    emit_dry_run: bool = True,
) -> RenderedScript:
    """渲染顶层串联脚本 run_all.sh + 可选 run_all.dry-run.sh。

    dry-run 版本调用各 tier 的 *.dry-run.sh 副本（preflight 仍走真实 login，
    因为 --validate=false 同样需要认证）。
    """
    ts = timestamp or _now_utc_iso()

    def _build(template: str, dry: bool) -> str:
        def fname(tier: Tier) -> str:
            base = TIER_FILES[tier]
            return _dry_filename(base) if dry else base

        infra_line = (
            f"bash {fname(Tier.INFRA_ROOT)}"
            if Tier.INFRA_ROOT in included_tiers else "# (no infra roots)"
        )
        root_line = (
            f"bash {fname(Tier.ROOT_APP)}"
            if Tier.ROOT_APP in included_tiers else "# (no app roots)"
        )
        workload_chunks = []
        if Tier.OPS_APP in included_tiers:
            workload_chunks.append(f"bash {fname(Tier.OPS_APP)}")
        if Tier.BUSINESS_APP in included_tiers:
            workload_chunks.append(f"bash {fname(Tier.BUSINESS_APP)}")
        workload_line = "\n".join(workload_chunks) if workload_chunks else "# (no workloads)"

        helm_line = (
            f"bash {fname(Tier.MULTI_SOURCE_HELM)}"
            if Tier.MULTI_SOURCE_HELM in included_tiers else "# (no multi-source helm apps)"
        )

        return template.format(
            timestamp=ts,
            infra_line=infra_line,
            root_line=root_line,
            workload_line=workload_line,
            helm_line=helm_line,
        )

    return RenderedScript(
        relative_path="run_all.sh",
        body=_build(RUN_ALL_SCRIPT, dry=False),
        dry_run_body=_build(RUN_ALL_DRY_SCRIPT, dry=True) if emit_dry_run else None,
    )


@dataclass
class RenderResult:
    scripts: list[RenderedScript] = field(default_factory=list)
    extras: list[ExtraFile] = field(default_factory=list)
    mapped_by_tier: dict[Tier, list[MappedApp]] = field(default_factory=dict)
    helm_apps: list[LoadedManifest] = field(default_factory=list)
    included_tiers: set[Tier] = field(default_factory=set)


def render_all(
    loaded: list[LoadedManifest],
    source_dir: Path,
    opts: RenderOptions,
    timestamp: str | None = None,
) -> RenderResult:
    """对所有 loaded manifest 按层级渲染脚本。

    省判定与 fallback 模块共用 ``fallback.reasons_for``——命中该函数返回非空原因列表的
    manifest 不会进入主脚本（避免与 99_multisource_fallback.yaml 重复创建/覆盖）。

    Tier.MULTI_SOURCE_HELM 由专用渲染路径处理：每个应用产生一份
    ``helm-apps/<name>.yaml`` 与一条 ``argocd app create -f`` 命令。

    timestamp 由调用方一次性提供（同一次 run 中所有产物使用同一时间戳）；
    缺省时模块内部自取一次以兼容直接调用场景。
    """
    ts = timestamp or _now_utc_iso()

    buckets: dict[Tier, list[LoadedManifest]] = {}
    for lm in loaded:
        if fallback.reasons_for(lm):
            continue
        buckets.setdefault(lm.tier, []).append(lm)

    result = RenderResult()
    result.scripts.append(render_preflight(timestamp=ts))

    for tier in (Tier.INFRA_ROOT, Tier.ROOT_APP, Tier.OPS_APP, Tier.BUSINESS_APP):
        items = buckets.get(tier) or []
        if not items:
            continue
        script, mapped_apps = _render_tier(tier, items, source_dir, opts, timestamp=ts)
        result.scripts.append(script)
        result.mapped_by_tier[tier] = mapped_apps
        result.included_tiers.add(tier)

    helm_items = buckets.get(Tier.MULTI_SOURCE_HELM) or []
    if helm_items:
        helm_script, helm_extras = _render_helm_multisource_tier(
            helm_items, source_dir, opts, timestamp=ts,
        )
        result.scripts.append(helm_script)
        result.extras.extend(helm_extras)
        result.helm_apps.extend(helm_items)
        result.included_tiers.add(Tier.MULTI_SOURCE_HELM)

    result.scripts.append(render_run_all(
        result.included_tiers, timestamp=ts, emit_dry_run=opts.emit_dry_run,
    ))
    return result


def write_results(result: RenderResult, output_dir: Path) -> list[Path]:
    """落盘所有脚本与附属 YAML，返回写入的文件路径列表。"""
    output_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    for script in result.scripts:
        path = output_dir / script.relative_path
        path.write_text(script.body, encoding="utf-8")
        path.chmod(0o755)
        written.append(path)

        if script.dry_run_body is not None:
            dry_name = script.relative_path.replace(".sh", ".dry-run.sh")
            dry_path = output_dir / dry_name
            dry_path.write_text(script.dry_run_body, encoding="utf-8")
            dry_path.chmod(0o755)
            written.append(dry_path)

    for extra in result.extras:
        path = output_dir / extra.relative_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(extra.body, encoding="utf-8")
        if extra.executable:
            path.chmod(0o755)
        written.append(path)

    return written
